#############################################################################
# Makefile for building: reghaabat
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat May 5 16:43:41 2012
# Project:  reghaabat.pro
# Template: app
# Command: d:/qt/qt/bin/qmake.exe -spec ../../Qt/qt/mkspecs/win32-g++ CONFIG+=release -o Makefile reghaabat.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = d:/qt/qt/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: reghaabat.pro  ../../Qt/qt/mkspecs/win32-g++/qmake.conf ../../Qt/qt/mkspecs/qconfig.pri \
		../../Qt/qt/mkspecs/modules/qt_webkit_version.pri \
		../../Qt/qt/mkspecs/features/qt_functions.prf \
		../../Qt/qt/mkspecs/features/qt_config.prf \
		../../Qt/qt/mkspecs/features/exclusive_builds.prf \
		../../Qt/qt/mkspecs/features/default_pre.prf \
		../../Qt/qt/mkspecs/features/win32/default_pre.prf \
		../../Qt/qt/mkspecs/features/release.prf \
		../../Qt/qt/mkspecs/features/debug_and_release.prf \
		../../Qt/qt/mkspecs/features/default_post.prf \
		../../Qt/qt/mkspecs/features/win32/default_post.prf \
		../../Qt/qt/mkspecs/features/win32/rtti.prf \
		../../Qt/qt/mkspecs/features/win32/exceptions.prf \
		../../Qt/qt/mkspecs/features/win32/stl.prf \
		../../Qt/qt/mkspecs/features/shared.prf \
		../../Qt/qt/mkspecs/features/warn_on.prf \
		../../Qt/qt/mkspecs/features/qt.prf \
		../../Qt/qt/mkspecs/features/win32/thread.prf \
		../../Qt/qt/mkspecs/features/moc.prf \
		../../Qt/qt/mkspecs/features/win32/windows.prf \
		../../Qt/qt/mkspecs/features/resources.prf \
		../../Qt/qt/mkspecs/features/uic.prf \
		../../Qt/qt/mkspecs/features/yacc.prf \
		../../Qt/qt/mkspecs/features/lex.prf \
		../../Qt/qt/mkspecs/features/include_source_dir.prf \
		d:/Qt/qt/lib/qtmain.prl
	$(QMAKE) -spec ../../Qt/qt/mkspecs/win32-g++ CONFIG+=release -o Makefile reghaabat.pro
../../Qt/qt/mkspecs/qconfig.pri:
../../Qt/qt/mkspecs/modules/qt_webkit_version.pri:
../../Qt/qt/mkspecs/features/qt_functions.prf:
../../Qt/qt/mkspecs/features/qt_config.prf:
../../Qt/qt/mkspecs/features/exclusive_builds.prf:
../../Qt/qt/mkspecs/features/default_pre.prf:
../../Qt/qt/mkspecs/features/win32/default_pre.prf:
../../Qt/qt/mkspecs/features/release.prf:
../../Qt/qt/mkspecs/features/debug_and_release.prf:
../../Qt/qt/mkspecs/features/default_post.prf:
../../Qt/qt/mkspecs/features/win32/default_post.prf:
../../Qt/qt/mkspecs/features/win32/rtti.prf:
../../Qt/qt/mkspecs/features/win32/exceptions.prf:
../../Qt/qt/mkspecs/features/win32/stl.prf:
../../Qt/qt/mkspecs/features/shared.prf:
../../Qt/qt/mkspecs/features/warn_on.prf:
../../Qt/qt/mkspecs/features/qt.prf:
../../Qt/qt/mkspecs/features/win32/thread.prf:
../../Qt/qt/mkspecs/features/moc.prf:
../../Qt/qt/mkspecs/features/win32/windows.prf:
../../Qt/qt/mkspecs/features/resources.prf:
../../Qt/qt/mkspecs/features/uic.prf:
../../Qt/qt/mkspecs/features/yacc.prf:
../../Qt/qt/mkspecs/features/lex.prf:
../../Qt/qt/mkspecs/features/include_source_dir.prf:
d:\Qt\qt\lib\qtmain.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../Qt/qt/mkspecs/win32-g++ CONFIG+=release -o Makefile reghaabat.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
